### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by guer0125** [guer0125/more-than-just-datum#2]
Could you guide me in the right direction, i know i have to do the grid system for them to work but i don't know where to start.

the heading is it a "form" and how do i do the search ?

thank you,

@mackenzierose

**Comment by MacKenzieRose** [comment]
For the grids, I would suggest setting this up as 2 grids; one for your navigation, and one for your main content.

The search bar is absolutely a form; to build it, you can treat the `search.svg` as an icon, and pin it in the label.

Does that help?
MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been addressed, please make sure to close it 😄
